### ISSUE TITLE
Recommended KB backlight patch and touchpad preset variable method

### ISSUE THREAD

**Issue by whatnameisit** [Nevuly/S510UA-BQ423-Hackintosh#1]
고생하셨고, 제 repo 사용해주셔서 감사합니다^^
1)키보드 백라이트랑 2)터치패드 손 보실 부분이 있을거예요.
1)백라이트는 hieplpvip의 AsusSMC repo (https://github.com/hieplpvip/AsusSMC/wiki/Installation-Instruction) 1.2 부분에 안정적인 16단계 조정 패치가 있어요. 그 패치 적용 후 부팅하고 fn+f3/fn+f4로 백라이트 조정 가능하면 완성이고, 그렇지 않으면 1.3 fn+f3/fn+f4 패치 적용하시면 됩니다. 후자의 경우 SSDT-X510UAKBLr.aml에 _SB.PCI0.LPCB.EC0에 _Q0C/_Q0D method 생성하고 패치 적용하시고, config.plist에 _Q0C-02/_Q0D-02 -> XQ0C-02/XQ0D-02 ACPI Rename 적용해주시면 됩니다.
2)SSDT-X510UA-Touchpad.aml은 제 터치패드 코드로 만든거라서, Nevuly님 터치패드 코드로 변경하시는게 안정적일거예요. SSDT의 _SB.PCI0.I2C1.ETXX에 _STA와 _CRS를 제외하고 나머지 부분이 DSDT와 일치하는지 확인해보시고, 같으면 그냥 두면 되지만 같지 않으면 DSDT 코드를 SSDT로 복사/대치해서 사용하시면 됩니다. 혹시 헷갈린다면 이 글 참고해보세요: https://x86.co.kr/tip/3770221
괜히 과제를 드린건 아닌지 싶네요...그래도 제 EFI를 베이스로 했을 때 내장될 수 있는 결함을 말씀드린거라서 한 번 확인해보시면 도움이 될 것 같습니다 ㅎㅎ;
즐커맥하세요 :)

**Comment by Nevuly** [comment]
도움 주셔서 감사합니다.

현재 바로 손보는게 불가능한 상태라서 ㅠㅠ

3주 뒤쯤 참고해서 손보고 업데이트 하겠습니다!

whatnameisit님 repo보면서 많이 배워갑니다.. :)

**Comment by Nevuly** [comment]
오늘 확인해 본 결과 키보드 백라이트는 AsusSMC의 패치만으로도 작동되는 걸 확인했고, 현재 터치패드도 이상은 없으나 iASL로 확인해보고 있습니다.

**Comment by Nevuly** [comment]
@whatnameisit 오늘 모든 코드 확인 완료했습니다.

다행이게도 터치패드와 FN키 전부 코드를 건들 필요가 없더군요 :)

DSDT.aml에서 전부 대조 확인 완료했고, 코드가 전부 동일함을 확인했습니다.

감사합니다!
