### ISSUE TITLE
잠자기 문제 

### ISSUE THREAD

**Issue by dayfly** [Nevuly/S510UA-BQ423-Hackintosh#2]
안녕하세요 이번에 여기 깃 참고하면서 해킨을 하고있는데 
잠자기가 안되서요 잠자기 문제는 USB 라고 하는데 혹시 USB 해결하는 방법이 없을까요??
잠자기에 들어가면 다시 꺠우면 화면은 검정색이고 커서만 있습니다 그리고 혼자 재부팅 되는데 알려주시면 감사합니다

**Comment by dayfly** [comment]
1	Name: Asus Vivobook S510UNR-BQ114
	2	CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	3	Graphics: Intel UHD Graphics 620 // Dual monitor with HDMI (Index 2) and 2048 MB VRAM
	4	Wifi: Intel Dual Band Wireless-AC 8265 - with bluetooth // REPLACED WITH bcm94360cs2 (AirDrop and Handoff Working perfectly)
	5	Card Reader: Alcor USB 2.0 Card Reader
	6	Camera: ASUS UVC HD
	7	Audio: Conexant Audio CX8050
	8	Touchpad: ELAN1300
	9	Bios Version: 308

**Comment by dayfly** [comment]
> 안녕하세요 이번에 여기 깃 참고하면서 해킨을 하고있는데
> 잠자기가 안되서요 잠자기 문제는 USB 라고 하는데 혹시 USB 해결하는 방법이 없을까요??
잠자기에 들어가면 다시 꺠우면 화면은 검정 화면이고 커서만 있다가 다시 재부팅이 됩니다

**Comment by Nevuly** [comment]
@dayfly 
일단, 제 깃에 있는 USBPorts.kext는 제 디바이스 기준으로 작성이 되어있습니다.
해당 켁스트를 먼저 지우시고,
새로운 USBPorts.kext를 작성하시려면 Hackintool을 사용하여 작성하시면 됩니다.

**Comment by dayfly** [comment]
> @dayfly
> 일단, 제 깃에 있는 USBPorts.kext는 제 디바이스 기준으로 작성이 되어있습니다.
> 해당 켁스트를 먼저 지우시고,
> 새로운 USBPorts.kext를 작성하시려면 Hackintool을 사용하여 작성하시면 됩니다.
USB 포트를 재 정의 할라고 해킨 툴을 켰는데 잘 안되더라고요 혹시 참고할만한곳 있나요??
해킨 툴로 USB 재 정의 한는곳이요

**Comment by Nevuly** [comment]
@dayfly 현재 제가 해킨을 안쓰는 중이라 정확하게 도움을 드리진 못하지만, 해킨툴로 들어가서 USB메뉴 탭에 들어간 다음 DW1560과 카메라를 Internal로 설정하신 다음 Export후, 켁스트만 넣고 재부팅 하시면 됩니다.
